// Auto-generated by OpenLane
module pipelined_mult(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[31:0] a,
  input[31:0] b,
  output[63:0] p
);
endmodule
