// Auto-generated by OpenLane
module add3x64(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[63:0] in1,
  input[63:0] in2,
  input[63:0] in3,
  output[63:0] out
);
endmodule
