// Auto-generated by OpenLane
module mult_16x16(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input[15:0] in1,
  input[15:0] in2,
  output[31:0] out
);
endmodule
